/*
 * Base de datos de tours
 * ----------------------
 * Itinerarios generados a partir de las rutas día a día de nuestro catálogo.
 * Sustituye precios, valoraciones y fotos por los datos reales de tu agencia
 * antes de publicar el sitio (ver README.md).
 *
 * Las imágenes usan picsum.photos como marcador de posición visual —
 * cámbialas por fotos reales de tus tours antes de publicar el sitio.
 */

const TOURS = [
  {
    slug: "3-dias-marrakech-fez-desierto",
    title: "3 Días: Marrakech a Fez por el Desierto",
    route: "Marrakech → Fez",
    days: 3,
    price: 125,
    currency: "€",
    rating: 4.8,
    reviews: 112,
    badge: "Clásico",
    excerpt: "Cruza el Alto Atlas, Ait Benhaddou y las gargantas de Todra camino al Sahara, con noche de campamento en Merzouga antes de llegar a Fez.",
    image: "https://github.com/user-attachments/assets/3f94634e-33ab-4bbc-8c33-45e4ccf59e93",
    category: "Marrakech",
    url: "tours/3-dias-marrakech-fez-desierto.html",
  },
  {
    slug: "4-dias-marrakech-fez-desierto",
    title: "4 Días: Marrakech a Fez por el Desierto",
    route: "Marrakech → Fez",
    days: 4,
    price: 165,
    currency: "€",
    rating: 4.9,
    reviews: 87,
    badge: "Recomendado",
    excerpt: "La misma ruta clásica de Marrakech a Fez, con un día extra de relax y exploración en las dunas de Merzouga.",
    image: "https://github.com/user-attachments/assets/08ac7531-19b5-4cd7-b019-8ad4e91864e9",
    category: "Marrakech",
    url: "tours/4-dias-marrakech-fez-desierto.html",
  },
  {
    slug: "2-dias-marrakech-merzouga-ida-vuelta",
    title: "2 Días: Marrakech a Merzouga (Ida y Vuelta)",
    route: "Marrakech → Marrakech",
    days: 2,
    price: 150,
    currency: "€",
    rating: 4.9,
    reviews: 112,
    badge: "Express",
    excerpt: "La forma más rápida de vivir el Sahara desde Marrakech: puerto de Tizi n'Tichka, Ait Benhaddou, camello al atardecer y una noche de campamento de lujo en Erg Chebbi.",
    image: "https://github.com/user-attachments/assets/cc0c1041-47cf-4668-a6f6-db51ab91cf92",
    category: "Marrakech",
    url: "tours/2-dias-marrakech-merzouga-ida-vuelta.html",
  },
  {
    slug: "3-dias-marrakech-merzouga-ida-vuelta",
    title: "3 Días: Marrakech a Merzouga (Ida y Vuelta)",
    route: "Marrakech → Marrakech",
    days: 3,
    price: 125,
    currency: "€",
    rating: 4.9,
    reviews: 134,
    badge: "Ida y vuelta",
    excerpt: "Ida y vuelta desde Marrakech: kasbahs del sur, gargantas del Dadès y una noche inolvidable en el campamento de Erg Chebbi.",
    image: "https://github.com/user-attachments/assets/cc0c1041-47cf-4668-a6f6-db51ab91cf92",
    category: "Marrakech",
    url: "tours/3-dias-marrakech-merzouga-ida-vuelta.html",
  },
  {
    slug: "4-dias-marrakech-merzouga-ida-vuelta",
    title: "4 Días: Marrakech a Merzouga (Ida y Vuelta)",
    route: "Marrakech → Marrakech",
    days: 4,
    price: 165,
    currency: "€",
    rating: 4.8,
    reviews: 76,
    badge: "Ida y vuelta",
    excerpt: "Una jornada extra para explorar el Valle del Draa y la kasbah de Telouet en tu ruta de ida y vuelta al desierto desde Marrakech.",
    image: "https://github.com/user-attachments/assets/4160f28e-b9e4-4db5-97a1-9aebad504706",
    category: "Marrakech",
    url: "tours/4-dias-marrakech-merzouga-ida-vuelta.html",
  },
  {
    slug: "5-dias-marrakech-fez",
    title: "5 Días: Marrakech a Fez",
    route: "Marrakech → Fez",
    days: 5,
    price: 200,
    currency: "€",
    rating: 4.9,
    reviews: 58,
    badge: "Más completo",
    excerpt: "Kasbah de Telouet, el Valle de las Rosas y dos noches en el desierto en un recorrido pausado de Marrakech a Fez.",
    image: "https://github.com/user-attachments/assets/7a334b34-115f-4a07-84fd-705b3f685a12",
    category: "Marrakech",
    url: "tours/5-dias-marrakech-fez.html",
  },
  {
    slug: "5-dias-marrakech-chefchaouen",
    title: "5 Días: Marrakech a Chefchaouen (vía Fez)",
    route: "Marrakech → Chefchaouen / Tánger",
    days: 5,
    price: 449,
    currency: "€",
    rating: 4.9,
    reviews: 47,
    badge: "Ciudad Azul",
    excerpt: "De las dunas de Erg Chebbi a la medina de Fez y las calles azules de Chefchaouen: el mejor resumen de Marruecos en 5 días.",
    image: "https://github.com/user-attachments/assets/b6c01b75-a72e-4abb-ae70-fea3f08938ac",
    category: "Marrakech",
    url: "tours/5-dias-marrakech-chefchaouen.html",
  },
  {
    slug: "3-dias-fez-marrakech-desierto",
    title: "3 Días: Fez a Marrakech por el Desierto",
    route: "Fez → Marrakech",
    days: 3,
    price: 125,
    currency: "€",
    rating: 4.8,
    reviews: 101,
    badge: "Clásico",
    excerpt: "La ruta clásica en sentido inverso: de Fez al Sahara y de vuelta a Marrakech por las kasbahs del sur.",
    image: "https://github.com/user-attachments/assets/22c7dcee-f3cf-4be9-a380-eb3348c15d06",
    category: "Fez",
    url: "tours/3-dias-fez-marrakech-desierto.html",
  },
  {
    slug: "4-dias-fez-marrakech-desierto",
    title: "4 Días: Fez a Marrakech por el Desierto",
    route: "Fez → Marrakech",
    days: 4,
    price: 165,
    currency: "€",
    rating: 4.9,
    reviews: 69,
    badge: "Recomendado",
    excerpt: "Un día extra para conocer Khamlia y a familias nómadas en tu viaje de Fez a Marrakech por el desierto.",
    image: "https://github.com/user-attachments/assets/6ef410c9-a94c-490c-9866-2a34e55670d1",
    category: "Fez",
    url: "tours/4-dias-fez-marrakech-desierto.html",
  },
  {
    slug: "5-dias-fez-marrakech",
    title: "5 Días: Fez a Marrakech",
    route: "Fez → Marrakech",
    days: 5,
    price: 200,
    currency: "€",
    rating: 4.8,
    reviews: 44,
    badge: "Recomendado",
    excerpt: "Mercado de Rissani, música gnawa en Khamlia y la kasbah de Telouet en cinco días de Fez a Marrakech.",
    image: "https://github.com/user-attachments/assets/e7a7a937-997b-4028-834d-57841b7cdf52",
    category: "Fez",
    url: "tours/5-dias-fez-marrakech.html",
  },
  {
    slug: "2-dias-fez-merzouga-express",
    title: "2 Días Express: Fez a Merzouga",
    route: "Fez → Fez",
    days: 2,
    price: 90,
    currency: "€",
    rating: 4.7,
    reviews: 158,
    badge: "Express",
    excerpt: "La forma más rápida de vivir el Sahara: una noche de campamento entre Fez y el desierto de Merzouga.",
    image: "https://github.com/user-attachments/assets/5b038a91-0031-466b-b9e9-5e7a3280b7ea",
    category: "Fez",
    url: "tours/2-dias-fez-merzouga-express.html",
  },
  {
    slug: "2-dias-marrakech-fez-express",
    title: "2 Días Express: Marrakech a Fez",
    route: "Marrakech → Fez",
    days: 2,
    price: 90,
    currency: "€",
    rating: 4.7,
    reviews: 121,
    badge: "Express",
    excerpt: "Cruza el Alto Atlas y el desierto de Merzouga en solo dos días de Marrakech a Fez.",
    image: "https://github.com/user-attachments/assets/e1142743-5a74-4608-8fb0-cdcd65d8abe6",
    category: "Marrakech",
    url: "tours/2-dias-marrakech-fez-express.html",
  },
  {
    slug: "5-dias-tanger-marrakech",
    title: "5 Días: Tánger a Marrakech",
    route: "Tánger → Marrakech",
    days: 5,
    price: 200,
    currency: "€",
    rating: 4.9,
    reviews: 39,
    badge: "Ruta norte",
    excerpt: "Chefchaouen, Volubilis y Fez antes de cruzar el desierto rumbo a Marrakech, partiendo desde Tánger.",
    image: "https://github.com/user-attachments/assets/4c15d663-974f-44a8-9af1-c10d0dfc0e58",
    category: "Tánger",
    url: "tours/5-dias-tanger-marrakech.html",
  },
  {
    slug: "6-dias-tanger-marrakech",
    title: "6 Días: Tánger a Marrakech",
    route: "Tánger → Marrakech",
    days: 6,
    price: 240,
    currency: "€",
    rating: 4.9,
    reviews: 27,
    badge: "Ruta norte",
    excerpt: "La ruta norte-sur completa con un día extra en Fez y sus zocos, desde Tánger hasta Marrakech.",
    image: "https://github.com/user-attachments/assets/3f94634e-33ab-4bbc-8c33-45e4ccf59e93",
    category: "Tánger",
    url: "tours/6-dias-tanger-marrakech.html",
  },
  {
    slug: "7-dias-gran-tour-marruecos",
    title: "7 Días: Gran Tour de Marruecos",
    route: "Casablanca/Tánger → Marrakech",
    days: 7,
    price: 280,
    currency: "€",
    rating: 5,
    reviews: 63,
    badge: "Gran Tour",
    excerpt: "Nuestro gran tour insignia: Chefchaouen, Fez, el Sahara y las kasbahs del sur en una sola semana.",
    image: "https://github.com/user-attachments/assets/08ac7531-19b5-4cd7-b019-8ad4e91864e9",
    category: "Casablanca",
    url: "tours/7-dias-gran-tour-marruecos.html",
  },
  {
    slug: "8-dias-itinerario-marruecos",
    title: "8 Días: Itinerario por Marruecos",
    route: "Casablanca → Casablanca",
    days: 8,
    price: 315,
    currency: "€",
    rating: 4.9,
    reviews: 31,
    badge: "Gran Tour",
    excerpt: "Rabat, Chefchaouen, Fez, el desierto y Marrakech: una semana y media para verlo prácticamente todo.",
    image: "https://github.com/user-attachments/assets/53e02f00-087b-4202-9d3e-f3978116458c",
    category: "Casablanca",
    url: "tours/8-dias-itinerario-marruecos.html",
  },
  {
    slug: "10-dias-itinerario-marruecos",
    title: "10 Días: Itinerario por Marruecos",
    route: "Casablanca → Marrakech",
    days: 10,
    price: 390,
    currency: "€",
    rating: 5,
    reviews: 22,
    badge: "Gran Tour",
    excerpt: "Diez días con tiempo de sobra para el desierto, las kasbahs y una escapada final a Essaouira.",
    image: "https://github.com/user-attachments/assets/85eebedf-6dc9-495e-8297-78c3bbaed4c7",
    category: "Casablanca",
    url: "tours/10-dias-itinerario-marruecos.html",
  },
  {
    slug: "12-dias-tour-completo-marruecos",
    title: "12 Días: Tour Completo de Marruecos",
    route: "Casablanca → Casablanca",
    days: 12,
    price: 470,
    currency: "€",
    rating: 4.9,
    reviews: 18,
    badge: "Completo",
    excerpt: "Doce días que añaden Tánger y una playa en Essaouira a nuestro recorrido más completo por Marruecos.",
    image: "https://github.com/user-attachments/assets/4160f28e-b9e4-4db5-97a1-9aebad504706",
    category: "Casablanca",
    url: "tours/12-dias-tour-completo-marruecos.html",
  },
  {
    slug: "14-dias-gran-circuito-marruecos",
    title: "14 Días: Gran Circuito de Marruecos",
    route: "Casablanca → Marrakech",
    days: 14,
    price: 545,
    currency: "€",
    rating: 5,
    reviews: 14,
    badge: "Circuito completo",
    excerpt: "Nuestro circuito más largo: costa, montaña, desierto y ciudades imperiales en dos semanas, con Taroudant y Essaouira incluidas.",
    image: "https://github.com/user-attachments/assets/7a334b34-115f-4a07-84fd-705b3f685a12",
    category: "Casablanca",
    url: "tours/14-dias-gran-circuito-marruecos.html",
  },
  {
    slug: "4-dias-ouarzazate-merzouga",
    title: "4 Días: Ouarzazate a Merzouga",
    route: "Ouarzazate → Ouarzazate",
    days: 4,
    price: 165,
    currency: "€",
    rating: 4.8,
    reviews: 33,
    badge: "Desde Ouarzazate",
    excerpt: "Ideal si llegas a Ouarzazate: oasis de Skoura, Valle de las Rosas y una noche en el Sahara antes de volver.",
    image: "https://github.com/user-attachments/assets/d7a97718-1325-4417-8eee-b988228dc708",
    category: "Ouarzazate",
    url: "tours/4-dias-ouarzazate-merzouga.html",
  },
  {
    slug: "3-dias-errachidia-fez",
    title: "3 Días: Errachidia a Fez vía Desierto de Merzouga",
    route: "Errachidia → Fez",
    days: 3,
    price: 125,
    currency: "€",
    rating: 4.8,
    reviews: 21,
    badge: "Desde Errachidia",
    excerpt: "Perfecto si aterrizas en Errachidia: te recogemos en el aeropuerto y en tres días te dejamos en Fez pasando por el Sahara.",
    image: "https://github.com/user-attachments/assets/22c7dcee-f3cf-4be9-a380-eb3348c15d06",
    category: "Errachidia",
    url: "tours/3-dias-errachidia-fez.html",
  },
  {
    slug: "2-dias-errachidia-merzouga-express",
    title: "2 Días Exprés: Errachidia al Desierto de Merzouga",
    route: "Errachidia → Errachidia",
    days: 2,
    price: 90,
    currency: "€",
    rating: 4.7,
    reviews: 18,
    badge: "Express",
    excerpt: "La forma más rápida de vivir el Sahara si aterrizas en Errachidia: una noche de campamento y vuelta al aeropuerto.",
    image: "https://github.com/user-attachments/assets/6ef410c9-a94c-490c-9866-2a34e55670d1",
    category: "Errachidia",
    url: "tours/2-dias-errachidia-merzouga-express.html",
  },
  {
    slug: "4-dias-errachidia-marrakech-desierto",
    title: "4 Días: Errachidia a Marrakech por el Desierto",
    route: "Errachidia → Marrakech",
    days: 4,
    price: 165,
    currency: "€",
    rating: 4.8,
    reviews: 14,
    badge: "Desde Errachidia",
    excerpt: "Fósiles de Erfoud, música gnawa en Khamlia y las kasbahs del sur en cuatro días de Errachidia a Marrakech.",
    image: "https://github.com/user-attachments/assets/e7a7a937-997b-4028-834d-57841b7cdf52",
    category: "Errachidia",
    url: "tours/4-dias-errachidia-marrakech-desierto.html",
  },
  {
    slug: "5-dias-errachidia-circuito-sur",
    title: "5 Días: Errachidia y Circuito Sur a Marrakech",
    route: "Errachidia → Marrakech",
    days: 5,
    price: 200,
    currency: "€",
    rating: 4.9,
    reviews: 9,
    badge: "Desde Errachidia",
    excerpt: "Un recorrido pausado desde Errachidia: exploración en 4x4 del desierto, el Valle de las Rosas y las kasbahs de Ouarzazate.",
    image: "https://github.com/user-attachments/assets/5b038a91-0031-466b-b9e9-5e7a3280b7ea",
    category: "Errachidia",
    url: "tours/5-dias-errachidia-circuito-sur.html",
  },
  {
    slug: "traslado-errachidia-merzouga",
    title: "Traslado Privado: Aeropuerto de Errachidia a Merzouga",
    route: "Errachidia → Merzouga",
    days: 1,
    price: 35,
    currency: "€",
    rating: 5,
    reviews: 6,
    badge: "Traslado privado",
    excerpt: "Traslado directo y privado desde el aeropuerto de Errachidia hasta tu campamento o alojamiento en Merzouga.",
    image: "https://github.com/user-attachments/assets/e1142743-5a74-4608-8fb0-cdcd65d8abe6",
    category: "Errachidia",
    url: "tours/traslado-errachidia-merzouga.html",
  },
  {
    slug: "traslado-errachidia-erfoud",
    title: "Traslado Privado: Aeropuerto de Errachidia a Erfoud",
    route: "Errachidia → Erfoud",
    days: 1,
    price: 25,
    currency: "€",
    rating: 5,
    reviews: 4,
    badge: "Traslado privado",
    excerpt: "Traslado directo y privado desde el aeropuerto de Errachidia hasta tu hotel o riad en Erfoud.",
    image: "https://github.com/user-attachments/assets/4c15d663-974f-44a8-9af1-c10d0dfc0e58",
    category: "Errachidia",
    url: "tours/traslado-errachidia-erfoud.html",
  },
  {
    slug: "6-dias-marrakech-fez-desierto",
    title: "6 Días: Marrakech a Fez por el Desierto",
    route: "Marrakech → Fez",
    days: 6,
    price: 245,
    currency: "€",
    rating: 4.9,
    reviews: 63,
    badge: "Circuito completo",
    excerpt: "El Alto Atlas, Ait Benhaddou, dos noches en el Sahara y una jornada guiada en la medina de Fez: el resumen más completo entre Marrakech y Fez.",
    image: "https://github.com/user-attachments/assets/3f94634e-33ab-4bbc-8c33-45e4ccf59e93",
    category: "Marrakech",
    url: "tours/6-dias-marrakech-fez-desierto.html",
  },
  {
    slug: "1-dia-atlas-esaouira",
    title: "Excursión de 1 Día: Atlas y Esaouira",
    route: "Marrakech (ida y vuelta)",
    days: 1,
    price: 45,
    currency: "€",
    rating: 4.6,
    reviews: 143,
    badge: "Día completo",
    excerpt: "Perfecto como complemento a tu desierto: costa atlántica, puerto de pescadores y la medina de Esaouira.",
    image: "https://picsum.photos/seed/atlas-esaouira-1d/640/480",
    category: "Marrakech",
    url: "tours/1-dia-atlas-esaouira.html",
  },
];

/* Utilidad compartida: formatea el precio con la moneda del tour */
function formatPrice(tour) {
  return `${tour.currency}${tour.price}`;
}
